name: CI

on:
  push:
    branches: [ "master", "ci-test"]
  pull_request:
    branches: [ "master" ]

jobs:
  guix-build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Make
      run: sudo apt-get install -y make
    - name: Install Guix
      uses: PromyLOPh/guix-install-action@v1.5
    - uses: actions/checkout@v3
    - name: guix build channel
      run: make build-channel
